// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement("h1", undefined, "Hello, world!"), "app");

/*  Not a pure module */
