// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Counter$ReactHooksTemplate = require("./Counter.bs.js");

import './app.css'
;

ReactDOMRe.renderToElementWithId(React.createElement(Counter$ReactHooksTemplate.make, { }), "app");

/*  Not a pure module */
